version: '3.7'

services:
  blockchain-bootnode:
    hostname: blockchain-bootnode
    env_file:
      - .env
    image: geth-client
    container_name: blockchain-bootnode
    build:
      context: .
      dockerfile: bootnode/Dockerfile
      args:
        - ACCOUNT_PASSWORD=${ACCOUNT_PASSWORD}
    command: --nodekeyhex="b0ac22adcad37213c7c565810a50f1772291e7b0ce53fb73e7ec2a3c75bc13b5" --nodiscover --ipcdisable --networkid=${NETWORK_ID} --netrestrict="172.25.0.0/24"
    networks:
      priv-eth-net:
        ipv4_address: 172.25.0.101

  rpc-endpoint:
    hostname: blockchain-rpc-endpoint
    env_file:
      - .env
    image: geth-client
    container_name: blockchain-rpc-endpoint
    depends_on:
      - blockchain-bootnode
    command: --bootnodes="enode://af22c29c316ad069cf48a09a4ad5cf04a251b411e45098888d114c6dd7f489a13786620d5953738762afa13711d4ffb3b19aa5de772d8af72f851f7e9c5b164a@blockchain-bootnode:30303" --allow-insecure-unlock --http --http.addr="0.0.0.0" --http.api="eth,web3,net,admin,personal" --http.corsdomain="*" --networkid=${NETWORK_ID} --netrestrict="172.25.0.0/24"
    ports:
      - "8545:8545"
    networks:
      priv-eth-net:
        ipv4_address: 172.25.0.102

  miner:
    hostname: blockchain-miner
    env_file:
      - .env
    image: geth-client
    container_name: blockchain-miner
    depends_on:
      - blockchain-bootnode
    command: --bootnodes="enode://af22c29c316ad069cf48a09a4ad5cf04a251b411e45098888d114c6dd7f489a13786620d5953738762afa13711d4ffb3b19aa5de772d8af72f851f7e9c5b164a@blockchain-bootnode:30303" --mine --miner.threads=1 --networkid=${NETWORK_ID} --netrestrict="172.25.0.0/24"
    networks:
      priv-eth-net:
        ipv4_address: 172.25.0.103

  frontend:
    hostname: frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: blockchain-frontend
    ports:
      - "8080:80"
    networks:
      priv-eth-net:
        ipv4_address: 172.25.0.104

networks:
  priv-eth-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24
